export const WhatsAppLimits = {
  MAX_REPLY_BUTTONS: 3,
  MAX_BUTTON_TITLE_LENGTH: 20,
  MAX_BUTTON_ID_LENGTH: 256,
  MAX_LIST_ROWS: 10,
  MAX_LIST_TITLE_LENGTH: 24,
  MAX_LIST_DESC_LENGTH: 72,
  MAX_LIST_BUTTON_TEXT_LENGTH: 20,
  MAX_LIST_HEADER_LENGTH: 60,
  MAX_BODY_TEXT_LENGTH: 4096,
};
